[package]
name = "wasm-edge"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
cn-font-split = { version = "7.0.0", path = "../.." }
wasm-bindgen = "0.2"
web-sys = "0.3.72"
