[package]
name = "wasm-edge"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
cn-font-proto = { version = "0.1.0", path = "../../crates/proto" }
cn-font-split = { version = "7.0.0", path = "../.." }
cn-font-utils = { version = "0.1.0", path = "../../crates/cn_font_utils" }
