[package]
name = "cn_font_split"
version = "7.0.0"
edition = "2021"

[dependencies]
harfbuzz_rs_now = "2.2.2"
log = "0.4.22"
md5 = "0.7.0"
opentype = "0.38.0"
prost = "0.13.3"
prost-types = { version = "0.13.3", optional = true }
unicode-range = { version = "0.1.0", path = "crates/unicode-range" }
woff = "0.3.3"

[dev-dependencies]
env_logger = "0.11.5"


[build-dependencies]
prost-build = "0.13.3"

[workspace]
members = [ "crates/lang_unicodes","crates/unicode-range"]
